/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChildrensBooksRouteImport } from './routes/childrens-books'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as BooksRouteImport } from './routes/books'
import { Route as AmbedkarThoughtsRouteImport } from './routes/ambedkar-thoughts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReadSlugRouteImport } from './routes/read.$slug'
import { Route as CategoriesSlugRouteImport } from './routes/categories.$slug'
import { Route as BooksSlugRouteImport } from './routes/books.$slug'

const ChildrensBooksRoute = ChildrensBooksRouteImport.update({
  id: '/childrens-books',
  path: '/childrens-books',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const AmbedkarThoughtsRoute = AmbedkarThoughtsRouteImport.update({
  id: '/ambedkar-thoughts',
  path: '/ambedkar-thoughts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadSlugRoute = ReadSlugRouteImport.update({
  id: '/read/$slug',
  path: '/read/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CategoriesRoute,
} as any)
const BooksSlugRoute = BooksSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BooksRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ambedkar-thoughts': typeof AmbedkarThoughtsRoute
  '/books': typeof BooksRouteWithChildren
  '/categories': typeof CategoriesRouteWithChildren
  '/childrens-books': typeof ChildrensBooksRoute
  '/books/$slug': typeof BooksSlugRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/read/$slug': typeof ReadSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ambedkar-thoughts': typeof AmbedkarThoughtsRoute
  '/books': typeof BooksRouteWithChildren
  '/categories': typeof CategoriesRouteWithChildren
  '/childrens-books': typeof ChildrensBooksRoute
  '/books/$slug': typeof BooksSlugRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/read/$slug': typeof ReadSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ambedkar-thoughts': typeof AmbedkarThoughtsRoute
  '/books': typeof BooksRouteWithChildren
  '/categories': typeof CategoriesRouteWithChildren
  '/childrens-books': typeof ChildrensBooksRoute
  '/books/$slug': typeof BooksSlugRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/read/$slug': typeof ReadSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ambedkar-thoughts'
    | '/books'
    | '/categories'
    | '/childrens-books'
    | '/books/$slug'
    | '/categories/$slug'
    | '/read/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ambedkar-thoughts'
    | '/books'
    | '/categories'
    | '/childrens-books'
    | '/books/$slug'
    | '/categories/$slug'
    | '/read/$slug'
  id:
    | '__root__'
    | '/'
    | '/ambedkar-thoughts'
    | '/books'
    | '/categories'
    | '/childrens-books'
    | '/books/$slug'
    | '/categories/$slug'
    | '/read/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AmbedkarThoughtsRoute: typeof AmbedkarThoughtsRoute
  BooksRoute: typeof BooksRouteWithChildren
  CategoriesRoute: typeof CategoriesRouteWithChildren
  ChildrensBooksRoute: typeof ChildrensBooksRoute
  ReadSlugRoute: typeof ReadSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/childrens-books': {
      id: '/childrens-books'
      path: '/childrens-books'
      fullPath: '/childrens-books'
      preLoaderRoute: typeof ChildrensBooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ambedkar-thoughts': {
      id: '/ambedkar-thoughts'
      path: '/ambedkar-thoughts'
      fullPath: '/ambedkar-thoughts'
      preLoaderRoute: typeof AmbedkarThoughtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read/$slug': {
      id: '/read/$slug'
      path: '/read/$slug'
      fullPath: '/read/$slug'
      preLoaderRoute: typeof ReadSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof CategoriesRoute
    }
    '/books/$slug': {
      id: '/books/$slug'
      path: '/$slug'
      fullPath: '/books/$slug'
      preLoaderRoute: typeof BooksSlugRouteImport
      parentRoute: typeof BooksRoute
    }
  }
}

interface BooksRouteChildren {
  BooksSlugRoute: typeof BooksSlugRoute
}

const BooksRouteChildren: BooksRouteChildren = {
  BooksSlugRoute: BooksSlugRoute,
}

const BooksRouteWithChildren = BooksRoute._addFileChildren(BooksRouteChildren)

interface CategoriesRouteChildren {
  CategoriesSlugRoute: typeof CategoriesSlugRoute
}

const CategoriesRouteChildren: CategoriesRouteChildren = {
  CategoriesSlugRoute: CategoriesSlugRoute,
}

const CategoriesRouteWithChildren = CategoriesRoute._addFileChildren(
  CategoriesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AmbedkarThoughtsRoute: AmbedkarThoughtsRoute,
  BooksRoute: BooksRouteWithChildren,
  CategoriesRoute: CategoriesRouteWithChildren,
  ChildrensBooksRoute: ChildrensBooksRoute,
  ReadSlugRoute: ReadSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
